-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 09:17:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` BIT NOT NULL,
  `comp_name` VARCHAR(20) NOT NULL,
  `comp_found_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`president`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`president` (
  `id` BIT NOT NULL,
  `pres_fname` VARCHAR(20) NOT NULL,
  `pres_lname` VARCHAR(20) NOT NULL,
  `pres_initial` VARCHAR(45) NOT NULL,
  `presidentcol` VARCHAR(3) NOT NULL,
  `pres_email_add` VARCHAR(50) NOT NULL,
  `pres_address` VARCHAR(100) NOT NULL,
  `pres_phone_num` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` BIT NOT NULL,
  `comp_name` VARCHAR(20) NOT NULL,
  `comp_found_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`warehouse` (
  `id` BIT NOT NULL,
  `wh_location` VARCHAR(30) NOT NULL,
  `wh_capacity` VARCHAR(20) NOT NULL,
  `wh_type` VARCHAR(20) NOT NULL,
  `wh_owner` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`president`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`president` (
  `id` BIT NOT NULL,
  `pres_fname` VARCHAR(20) NOT NULL,
  `pres_lname` VARCHAR(20) NOT NULL,
  `pres_initial` VARCHAR(45) NOT NULL,
  `presidentcol` VARCHAR(3) NOT NULL,
  `pres_email_add` VARCHAR(50) NOT NULL,
  `pres_address` VARCHAR(100) NOT NULL,
  `pres_phone_num` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`finance manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`finance manager` (
  `id` BIT NOT NULL,
  `fm_fname` VARCHAR(20) NOT NULL,
  `fm_lname` VARCHAR(20) NOT NULL,
  `fm_initial` VARCHAR(3) NOT NULL,
  `fm_email_add` VARCHAR(50) NULL,
  `fm_phone_num` INT(11) NULL,
  `president_id` BIT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_finance manager_president_idx` (`president_id` ASC) VISIBLE,
  CONSTRAINT `fk_finance manager_president1`
    FOREIGN KEY (`president_id`)
    REFERENCES `mydb`.`president` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`president`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`president` (
  `id` BIT NOT NULL,
  `pres_fname` VARCHAR(20) NOT NULL,
  `pres_lname` VARCHAR(20) NOT NULL,
  `pres_initial` VARCHAR(45) NOT NULL,
  `presidentcol` VARCHAR(3) NOT NULL,
  `pres_email_add` VARCHAR(50) NOT NULL,
  `pres_address` VARCHAR(100) NOT NULL,
  `pres_phone_num` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT(5) NOT NULL,
  `cl_fname` VARCHAR(20) NOT NULL,
  `cl_lname` VARCHAR(20) NOT NULL,
  `cl_initial` VARCHAR(3) NOT NULL,
  `cl_email_add` VARCHAR(50) NULL,
  `cl_phone_number` INT(11) NULL,
  `cl_type` VARCHAR(20) NULL,
  `president_id` BIT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_president1_idx` (`president_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_president1`
    FOREIGN KEY (`president_id`)
    REFERENCES `mydb`.`president` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` BIT NOT NULL,
  `comp_name` VARCHAR(20) NOT NULL,
  `comp_found_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT(5) NOT NULL,
  `emp_fname` VARCHAR(20) NOT NULL,
  `emp_lname` VARCHAR(20) NOT NULL,
  `emp_initial` VARCHAR(3) NOT NULL,
  `emp_email_add` VARCHAR(50) NULL,
  `emp_phone_number` INT(11) NULL,
  `emp_type` VARCHAR(20) NOT NULL,
  `employee type_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_employee type1_idx` (`employee type_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_employee type1`
    FOREIGN KEY (`employee type_id`)
    REFERENCES `mydb`.`employee type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`warehouse` (
  `id` BIT NOT NULL,
  `wh_location` VARCHAR(30) NOT NULL,
  `wh_capacity` VARCHAR(20) NOT NULL,
  `wh_type` VARCHAR(20) NOT NULL,
  `wh_owner` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hr and sc manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hr and sc manager` (
  `id` BIT NOT NULL,
  `hsm_fname` VARCHAR(20) NOT NULL,
  `hsm_lname` VARCHAR(20) NOT NULL,
  `hsm_initial` VARCHAR(3) NOT NULL,
  `hsm_email_add` VARCHAR(50) NULL,
  `hsm_phone_number` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`president`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`president` (
  `id` BIT NOT NULL,
  `pres_fname` VARCHAR(20) NOT NULL,
  `pres_lname` VARCHAR(20) NOT NULL,
  `pres_initial` VARCHAR(45) NOT NULL,
  `presidentcol` VARCHAR(3) NOT NULL,
  `pres_email_add` VARCHAR(50) NOT NULL,
  `pres_address` VARCHAR(100) NOT NULL,
  `pres_phone_num` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hr and sc manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hr and sc manager` (
  `id` BIT NOT NULL,
  `hsm_fname` VARCHAR(20) NOT NULL,
  `hsm_lname` VARCHAR(20) NOT NULL,
  `hsm_initial` VARCHAR(3) NOT NULL,
  `hsm_email_add` VARCHAR(50) NULL,
  `hsm_phone_number` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hr and sc manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hr and sc manager` (
  `id` BIT NOT NULL,
  `hsm_fname` VARCHAR(20) NOT NULL,
  `hsm_lname` VARCHAR(20) NOT NULL,
  `hsm_initial` VARCHAR(3) NOT NULL,
  `hsm_email_add` VARCHAR(50) NULL,
  `hsm_phone_number` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT(5) NOT NULL,
  `emp_fname` VARCHAR(20) NOT NULL,
  `emp_lname` VARCHAR(20) NOT NULL,
  `emp_initial` VARCHAR(3) NOT NULL,
  `emp_email_add` VARCHAR(50) NULL,
  `emp_phone_number` INT(11) NULL,
  `emp_type` VARCHAR(20) NOT NULL,
  `employee type_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_employee type1_idx` (`employee type_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_employee type1`
    FOREIGN KEY (`employee type_id`)
    REFERENCES `mydb`.`employee type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee type` (
  `id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT(5) NOT NULL,
  `emp_fname` VARCHAR(20) NOT NULL,
  `emp_lname` VARCHAR(20) NOT NULL,
  `emp_initial` VARCHAR(3) NOT NULL,
  `emp_email_add` VARCHAR(50) NULL,
  `emp_phone_number` INT(11) NULL,
  `emp_type` VARCHAR(20) NOT NULL,
  `employee type_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_employee type1_idx` (`employee type_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_employee type1`
    FOREIGN KEY (`employee type_id`)
    REFERENCES `mydb`.`employee type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
